# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - vaswebgit2

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://vasregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_2ebdd92027924b539fe378ec037a7c15 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_666897eb19c8403eaec3266c75cc0947 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: vasregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_2ebdd92027924b539fe378ec037a7c15 }}/vasregistry/get-net:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'vaswebgit2'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3be969c6939b4e029caf78fd14e92fa6 }}
        images: 'vasregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_2ebdd92027924b539fe378ec037a7c15 }}/vasregistry/get-net:${{ github.sha }}'